image: Ubuntu

stack: jdk 11
branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar& -port=8888
  - chmod +x gradlew

build_script:
  - ./gradlew test --info